# Core configuration Error
E30001: Vert.x zero server config is missing in current data "{0}"
# Configuration validation Error
E10001: (V) - This rule require all elements of array is JsonObject, Now the index = {0} does not match, it''s {1}
E10002: (V) - The data object {0} missed required field "{1}"
E10003: (V) - The field {0} value is "{1}", but expected type is "{2}"
E10004: (V) - The cluster options is enabled, but the "{0}" vertx instance = "{1}"
E10005: (V) - The dynamic key "{0}" missing in uniform extension configuration data {1}
E10006: (V) - The data object {0} contains unsupported/forbidden field "{1}"
# (Runtime) Vertx start up error
E40001: Vert.x zero boot class should not be null, please provide the entry of this application
E40002: Vert.x zero boot class must be marked with annotation "Up", but ( name= {0} ) it''s missing
E40003: ZeroLauncher require input callback to handle vertx reference, but not it''s null
E40004: You have defined {0} agent {2} for server of type {1}, it''s fobbiden
E40005: Event extractor only accept to scan class of @EndPoint, but now it''s {0}
E40006: PathResolver could not accept null pointer reference of @Path
E40007: MethodResolver could not accept null pointer reference of Method
E40008: The event handler of path {0} has not been set, please verify configuration
E40009: Vert.x zero require class {0} contains at least one no-arg constructor, but now it''s missing
E40010: Vert.x zero require class {0} access modifier contains PUBLIC scope, but now it couldn't be accessed
E40011: Vert.x zero found method parameters without any annotated, it's conflict. Type = {0}
E40012: The address {0} does not existing in incoming address list. Position - type = {1}, method = {2}
E40013: You want to send message to event bus, but agent method ({0}) of {1}''s return type is (void)
E40014: Zero detected that there is no method of @Queue annotated @Address = {0}, the worker missing
E40015: Plugin component met error when reading option on key = {0}
E40016: You enabled the plugin ( key = {0} ), but this plugin has no method of ( public static void init(Vertx) )
E40017: Worker method signature is wrong, the parameter length must be 1. method = {0}, class = {1}
E40018: "Async mode: return = {0}, parameter = {1}, valid - Envelop method(Envelop), void method(Message<Envelop>;)"
E40019: Your plugin {0} met error when starting, please check the details {1}
E40020: Zero system could not find the config of key = {0}, please check your configurations
E40021: The field "{0}" of class {1} has been annotated with Zero annotation more than once, data = {2}
E40023: "Zero system found field \"{0}\" of class {1} is interface with non-unique implementation, but @Qualifier missed"
E40024: "One of the classes \"{0}\" missed @Named annotation, because they implement the same interface {1}"
E40025: "All the implementation class \"{0}\" with @Named contains no value of \"{1}\""
E40026: "You will initialize infix = \"{0}\", but the configuration missed \"{1}\" in lime node of vertx.xml"
E40027: "You are trying to initialize EtcdClient, but the configuration data is empty."
E40028: Duplicated implementation of interface \"{0}\" found in the system, it''s invalid
E40029: The annotation {1} occurs {2} times in the method {0}, it''s forbidden in zero system
E40030: The {0} parameter annotation should select one category, but now zero system detect {1}
E40031: The {0} parameter annotation is {1}, but the java type {2} is not supported here
E40032: You are in mode "Direct", the input index must be greatter and equal to 0, current is {0}
E40033: "(Database) You are trying to initialize \"Xtor\" component, but found invalid component {0} in method {1}"
E40034: "(Database) Your \"Xtor\" component is not ready, (client, clazz, logger, collection) could not be null"
E40035: "(Database) You are executing the operations in \"Xtor\" component, but met error: {0}"
E40036: (Rpc) Zero rpc require SSL with Alpn enabled, please check your configuration of port = {0}, options = {1}
E40037: (Rpc) Enabled in current environment, but remote configuration center ( Etcd ) is not prepared
E40038: "(Security) Zero system detected duplicated \"Wall\" classes [{0}] (Path & Order) should not be the same, it''s invalid"
E40039: "The network configured for etcd ( host = {0}, port = {1} ) could not be reached"
E40040: "(Security) You have configured key = \"{0}\" in @Wall class {1}, but it''s missing"
E40041: "(Security) Every @Wall class must contains only one method annotated with {0}, current {1} contains more"
E40042: "You have enabled @Address and @Ipc both on method \"{0}\" of class \"{1}\", only one channel should be valid."
# (Web) Exception for web
E60000: (400) - Request validation failure, class = {0}, method = {1}, message = {2}
E60001: (400) - The input content could not be converted into valid resource user {0}
E60002: (500) - The system detect some error in delivery on address {0}, error message = {1}
E60003: (500) - The event bus detect some error in receiving message on address {0}, error message = {1}
E60004: (400) - Zero system detect conversation from "{0}" to type "{1}", but it's conflict
E60005: (400) - Request body validation failure, field = {0}, value = {1}, message = {2}
E60006: (400) - Server could not accept the mime "{0}", expected should be one of {1}
E60007: (500) - The system detected internal error, contact administrator and check details = {0}
E60008: (404) - Zero system detect non record in storage, no record
E60009: (400) - Zero system detect duplicated records in storage, size = {0}
E60010: (404) - The request {0} of method {1} could not be found in zero system
E60011: "(400) - (Security) Zero system detected invalid request in request"
E60012: "(401) - (Security) Unauthorized request met in request"
E60013: "(403) - (Security) Access denied/forbidden in request"
E60014: "(405) - The method \"{0}\" for request uri {1} is not allowed"
E60015: "(501) - The service ( name = {0}, address = {1}, method = {2}, class = {3} ) could not be found"
E60016: "(501) - The service address = {0} is wrong in name = {1}"
E60017: "(504) - The remote service ( location = {0}, name = {1} ) met error, details = {2}"
E60018: "(501) - The micro service could not find method by address = {0}, error occurs"